language: java

sudo: false

script: "mvn clean install -Denv=travis"

before_install:
  - mysql -e "create database IF NOT EXISTS taschengeldboerse;CREATE USER 'boersenadmin'@'%' IDENTIFIED BY 'admin2015!';GRANT ALL PRIVILEGES ON taschengeldboerse.* TO 'boersenadmin'@'%';" -uroot
